### ISSUE TITLE
add new IPMI errata #6 IPv6 support into libfreeipmi

### ISSUE THREAD

**Issue by chu11** [chu11/freeipmi-mirror#11]
This is a fork off of issue #8   

Here's some initial thoughts on the more manual activities that have to be done to get IPv6 support into ipmi-config.  Some times unknown w/ quesiton marks attached

libfreeipmi/include/freeipmi/spec/ipmi-lan-configuration-parameters-spec.h
- [ ] - Table 23-4 new IPv6 configs

libfreeipmi/include/freeipmi/cmds/ipmi-lan-cmds.h
libfreeipmi/cmds/ipmi-lan-cmds.c
- [ ] - Table 23-4 new templates
- [ ] - Table 23-4 new fill functions
- [ ] - new macros needed for config parameters/options?

libfreeipmi/include/freeipmi/templates/ipmi-lan-cmds-templates.h
- [ ] - document new templates

libfreeipmi/include/freeipmi/api/ipmi-lan-cmds-api.h
libfreeipmi/api/ipmi-lan-cmds-api.c
- [ ] - Table 23-4 new API equivalents

23.2a DHCPv6 Timing Parameters
- [ ] - macros/enums needed?

23.2b Neighbor Discovery / SLAAC Timing Parameters
- [ ] - macros/enums needed?

**Comment by lamontj** [comment]
My ipv6 branch has (untested) configs and fill functions for your review -- no new templates yet, though.

**Comment by chu11** [comment]
@lamontj Could you just go ahead and send a pull request.  It's easier to review/comment via the PR review system.

**Comment by lamontj** [comment]
@chu11 Before I write fill functions, can I get feedback on the configs and templates?  After that I may go for full-depth on a few of the config variables, so that I can get fully familiar with the path earlier.

**Comment by chu11** [comment]
@lamontj that's my plan, will review hopefully starting tonight

**Comment by chu11** [comment]
Hey @lamontj, just looking over things, and noticed the "commit" parts of the IPv6 in ipmi-config were never completed.  Is this still on your todo?

**Comment by chu11** [comment]
majority of this is complete, discounting a few DHCP/dynamic IPv6 stuff.  Will add if needed.  Considering this done.
