### ISSUE TITLE
Hardcoded sbindir in systemd units

### ISSUE THREAD

**Issue by grawlinson** [chu11/freeipmi-mirror#41]
`/usr/sbin` is hardcoded in systemd units, so the path specified when running `./configure --sbindir=/other/sbin/path` is not respected.

All service files in [etc](https://github.com/chu11/freeipmi-mirror/tree/master/etc) seem to be affected.

**Comment by chu11** [comment]
doh!  but an easy fix.  Will get this into the next release.

**Comment by chu11** [comment]
@grawlinson i think I got it working.  I've pushed into the master branch both here and on savannah.  Could you give it a quick skim?  Just in case I missed a case.

**Comment by grawlinson** [comment]
Looks good to me! 👍

**Comment by chu11** [comment]
great, i'll backport to 1.6.X line and it'll be in the next release.
