### ISSUE TITLE
1.6.10 release

### ISSUE THREAD

**Issue by Fantu** [chu11/freeipmi-mirror#54]
Hi, is there any ETA about 1.6.10 release?
IPv6 patches was applied on debian (and derivates) packages 6 months ago and used also in latest ubuntu LTS (jammy), I created also a backport for debian 11 and ubuntu 20.04, for now on debian and ubuntu bugtracker no issue was reported related to it

**Comment by chu11** [comment]
hey @Fantu, no specific ETA, but since you've requested, I'll go ahead and do a release.  Maybe this afternoon, minimally this week.

**Comment by chu11** [comment]
out on the FreeIPMI website this morning
